import type { LucideIcon } from "lucide-react";
import {
  BadgeDollarSign,
  Banknote,
  Bike,
  BriefcaseBusiness,
  Car,
  Cigarette,
  CircleEllipsis,
  CreditCard,
  FileText,
  Fuel,
  Gift,
  HeartHandshake,
  HeartPulse,
  Home,
  Leaf,
  Package,
  Package2,
  Paintbrush,
  PawPrint,
  Pill,
  Printer,
  Receipt,
  ShoppingCart,
  Sparkles,
  Store,
  Utensils,
  Wallet,
  Wine,
  Wrench,
  Zap,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  wallet: Wallet,
  "heart-handshake": HeartHandshake,
  home: Home,
  cigarette: Cigarette,
  leaf: Leaf,
  wine: Wine,
  utensils: Utensils,
  "shopping-cart": ShoppingCart,
  car: Car,
  receipt: Receipt,
  pill: Pill,
  sparkles: Sparkles,
  "badge-dollar-sign": BadgeDollarSign,
  gift: Gift,
  "paw-print": PawPrint,
  "heart-pulse": HeartPulse,
  "circle-ellipsis": CircleEllipsis,
  "credit-card": CreditCard,
  banknote: Banknote,
  "briefcase-business": BriefcaseBusiness,
  fuel: Fuel,
  wrench: Wrench,
  bike: Bike,
  printer: Printer,
  paintbrush: Paintbrush,
  package: Package,
  "package-2": Package2,
  store: Store,
  zap: Zap,
  "file-text": FileText,
};

export function getIcon(name: string) {
  return iconMap[name] ?? CircleEllipsis;
}
