import { addDays, format, setDate, startOfMonth, subDays } from "date-fns";

import { appName, appVersion, categoryPresets, schemaVersion } from "@/lib/constants";
import { roundCurrency, slugify } from "@/lib/utils";
import type {
  AppSettings,
  Budget,
  Category,
  CostCenter,
  CreditCard,
  FilamentSpool,
  FuelLog,
  Income,
  MaintenanceLog,
  OperationalSettings,
  ProductionJob,
  ProductionMaterialUsage,
  RecurrenceRule,
  StockMovement,
  StoreOrder,
  SupplyItem,
  Transaction,
  TransactionInstallment,
  Vehicle,
  WorkspaceSnapshot,
} from "@/types/domain";
import { generateInstallmentsForTransaction } from "@/utils/installments";

type SeedContext =
  | "local"
  | "supabase"
  | {
      storageMode: "local" | "supabase";
      workspaceId?: string;
      workspaceName?: string;
      userId?: string;
      username?: string;
      displayName?: string;
      email?: string;
    };

function timestamp(days = 0) {
  return format(addDays(new Date(), days), "yyyy-MM-dd'T'HH:mm:ssxxx");
}

function round(value: number) {
  return roundCurrency(value);
}

export function createSeedSnapshot(input: SeedContext): WorkspaceSnapshot {
  const context = typeof input === "string" ? { storageMode: input } : input;
  const now = timestamp();
  const storageMode = context.storageMode;
  const workspaceId = context.workspaceId ?? "workspace_home";
  const workspaceName = context.workspaceName ?? appName;
  const userId = context.userId ?? "user_owner";
  const username = context.username ?? "mark";
  const displayName = context.displayName ?? "Mark";
  const email = context.email ?? "mark@example.com";
  const monthStart = startOfMonth(new Date());
  const currentMonth = format(monthStart, "yyyy-MM");
  const centerIds = {
    me: "profile_me",
    partner: "profile_partner",
    shared: "profile_shared",
    moto: "center_moto",
    store: "center_store",
  };

  const costCenters: CostCenter[] = [
    {
      id: centerIds.me,
      workspaceId,
      kind: "me",
      name: "Eu",
      color: "#10b981",
      icon: "wallet",
      active: true,
      module: "finance",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: centerIds.partner,
      workspaceId,
      kind: "partner",
      name: "Namorada",
      color: "#06b6d4",
      icon: "heart-handshake",
      active: true,
      module: "finance",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: centerIds.shared,
      workspaceId,
      kind: "shared",
      name: "Casal",
      color: "#8b5cf6",
      icon: "home",
      active: true,
      module: "shared",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: centerIds.moto,
      workspaceId,
      kind: "moto",
      name: "Moto",
      color: "#f59e0b",
      icon: "bike",
      active: true,
      module: "moto",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: centerIds.store,
      workspaceId,
      kind: "store",
      name: "Loja",
      color: "#22c55e",
      icon: "printer",
      active: true,
      module: "store",
      createdAt: now,
      updatedAt: now,
    },
  ];

  const categories: Category[] = categoryPresets.map((preset, index) => ({
    id: `category_${index + 1}`,
    workspaceId,
    name: preset.name,
    slug: slugify(preset.name),
    color: preset.color,
    icon: preset.icon,
    keywords: preset.keywords,
    budgetable: preset.budgetable,
    system: true,
    scope: preset.scope,
    createdAt: now,
    updatedAt: now,
  }));

  const getCategory = (slug: string) =>
    categories.find((item) => item.slug === slug)?.id ?? categories[0].id;

  const cards: CreditCard[] = [
    {
      id: "card_nubank",
      workspaceId,
      name: "Nubank",
      brand: "Mastercard",
      last4: "5472",
      limit: 2200,
      bestPurchaseDay: 12,
      dueDay: 19,
      color: "#8b5cf6",
      aliases: ["nubank", "nu", "roxinho"],
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "card_inter",
      workspaceId,
      name: "Inter",
      brand: "Visa",
      last4: "1038",
      limit: 1500,
      bestPurchaseDay: 7,
      dueDay: 14,
      color: "#f97316",
      aliases: ["inter", "laranja"],
      active: true,
      createdAt: now,
      updatedAt: now,
    },
  ];

  const transactions: Transaction[] = [
    {
      id: "tx_smoke",
      workspaceId,
      centerId: centerIds.me,
      categoryId: getCategory("cigarro"),
      description: "Cigarro da semana",
      amount: 38,
      paymentMethod: "debit",
      transactionDate: subDays(new Date(), 2).toISOString().slice(0, 10),
      installments: 1,
      originModule: "finance",
      originRefId: null,
      lockedByOrigin: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx_lunch",
      workspaceId,
      centerId: centerIds.me,
      categoryId: getCategory("alimentacao"),
      description: "Almoço no VR",
      amount: 24.9,
      paymentMethod: "vr",
      transactionDate: subDays(new Date(), 1).toISOString().slice(0, 10),
      installments: 1,
      originModule: "finance",
      originRefId: null,
      lockedByOrigin: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx_market",
      workspaceId,
      centerId: centerIds.shared,
      categoryId: getCategory("mercado"),
      description: "Compra do mercado",
      amount: 148.35,
      paymentMethod: "pix",
      transactionDate: subDays(new Date(), 5).toISOString().slice(0, 10),
      installments: 1,
      originModule: "finance",
      originRefId: null,
      lockedByOrigin: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx_weed",
      workspaceId,
      centerId: centerIds.me,
      categoryId: getCategory("ervas"),
      description: "Ervas do mês",
      amount: 60,
      paymentMethod: "pix",
      transactionDate: subDays(new Date(), 8).toISOString().slice(0, 10),
      installments: 1,
      originModule: "finance",
      originRefId: null,
      lockedByOrigin: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx_pharmacy",
      workspaceId,
      centerId: centerIds.partner,
      categoryId: getCategory("farmacia"),
      description: "Farmácia",
      amount: 42,
      paymentMethod: "debit",
      transactionDate: subDays(new Date(), 3).toISOString().slice(0, 10),
      installments: 1,
      originModule: "finance",
      originRefId: null,
      lockedByOrigin: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx_rent",
      workspaceId,
      centerId: centerIds.shared,
      categoryId: getCategory("aluguel"),
      description: "Aluguel",
      amount: 750,
      paymentMethod: "pix",
      transactionDate: format(setDate(monthStart, 5), "yyyy-MM-dd"),
      installments: 1,
      originModule: "finance",
      originRefId: null,
      lockedByOrigin: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx_drinks_installment",
      workspaceId,
      centerId: centerIds.partner,
      categoryId: getCategory("bebidas"),
      description: "Bebidas em 3x",
      amount: 126,
      paymentMethod: "credit",
      transactionDate: subDays(new Date(), 4).toISOString().slice(0, 10),
      cardId: "card_nubank",
      installments: 3,
      originModule: "finance",
      originRefId: null,
      lockedByOrigin: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx_fuel_1",
      workspaceId,
      centerId: centerIds.moto,
      categoryId: getCategory("combustivel"),
      description: "Abastecimento Shell",
      amount: 78,
      paymentMethod: "debit",
      transactionDate: subDays(new Date(), 1).toISOString().slice(0, 10),
      installments: 1,
      originModule: "moto",
      originRefId: "fuel_1",
      lockedByOrigin: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx_maint_1",
      workspaceId,
      centerId: centerIds.moto,
      categoryId: getCategory("manutencao-moto"),
      description: "Troca de óleo + filtro",
      amount: 120,
      paymentMethod: "pix",
      transactionDate: subDays(new Date(), 10).toISOString().slice(0, 10),
      installments: 1,
      originModule: "moto",
      originRefId: "maint_1",
      lockedByOrigin: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx_store_filament_batch",
      workspaceId,
      centerId: centerIds.store,
      categoryId: getCategory("filamento"),
      description: "Compra agrupada de filamentos",
      amount: 200,
      paymentMethod: "pix",
      transactionDate: subDays(new Date(), 14).toISOString().slice(0, 10),
      installments: 1,
      originModule: "store",
      originRefId: "stock_batch_filament_1",
      lockedByOrigin: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tx_store_supplies",
      workspaceId,
      centerId: centerIds.store,
      categoryId: getCategory("pintura-e-acabamento"),
      description: "Compra de primer, verniz e embalagens",
      amount: 66,
      paymentMethod: "pix",
      transactionDate: subDays(new Date(), 12).toISOString().slice(0, 10),
      installments: 1,
      originModule: "store",
      originRefId: "stock_supply_batch_1",
      lockedByOrigin: true,
      createdAt: now,
      updatedAt: now,
    },
  ];

  const installments: TransactionInstallment[] = generateInstallmentsForTransaction({
    transaction: transactions.find((item) => item.id === "tx_drinks_installment")!,
    card: cards[0],
    workspaceId,
    createdAt: now,
  });

  const incomes: Income[] = [
    {
      id: "income_salary",
      workspaceId,
      centerId: centerIds.shared,
      description: "Salário CLT",
      amount: 2000,
      incomeType: "salary",
      wallet: "cash",
      receivedAt: format(setDate(monthStart, 5), "yyyy-MM-dd"),
      originModule: "finance",
      originRefId: null,
      lockedByOrigin: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "income_vr",
      workspaceId,
      centerId: centerIds.shared,
      description: "VR mensal",
      amount: 800,
      incomeType: "vr",
      wallet: "vr",
      receivedAt: format(setDate(monthStart, 3), "yyyy-MM-dd"),
      originModule: "finance",
      originRefId: null,
      lockedByOrigin: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "income_freela",
      workspaceId,
      centerId: centerIds.me,
      description: "Freela rápido",
      amount: 180,
      incomeType: "freelance",
      wallet: "cash",
      receivedAt: subDays(new Date(), 6).toISOString().slice(0, 10),
      originModule: "finance",
      originRefId: null,
      lockedByOrigin: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "income_store_order_1",
      workspaceId,
      centerId: centerIds.store,
      description: "Pedido entregue - topo Stitch",
      amount: 144,
      incomeType: "sale",
      wallet: "cash",
      receivedAt: subDays(new Date(), 2).toISOString().slice(0, 10),
      originModule: "store",
      originRefId: "order_1",
      lockedByOrigin: true,
      createdAt: now,
      updatedAt: now,
    },
  ];

  const budgetsSeed: Array<[string, number]> = [
    ["cigarro", 300],
    ["bebidas", 250],
    ["ervas", 200],
    ["lazer", 280],
    ["alimentacao", 500],
    ["outros", 200],
  ];

  const budgets: Budget[] = budgetsSeed.map(([slug, limit], index) => ({
    id: `budget_${index + 1}`,
    workspaceId,
    categoryId: getCategory(slug),
    month: currentMonth,
    limit,
    createdAt: now,
    updatedAt: now,
  }));

  const recurrences: RecurrenceRule[] = [
    {
      id: "rec_salary",
      workspaceId,
      kind: "income",
      frequency: "monthly",
      interval: 1,
      startDate: format(setDate(monthStart, 5), "yyyy-MM-dd"),
      description: "Salário CLT",
      amount: 2000,
      centerId: centerIds.shared,
      incomeType: "salary",
      wallet: "cash",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "rec_vr",
      workspaceId,
      kind: "income",
      frequency: "monthly",
      interval: 1,
      startDate: format(setDate(monthStart, 3), "yyyy-MM-dd"),
      description: "VR mensal",
      amount: 800,
      centerId: centerIds.shared,
      incomeType: "vr",
      wallet: "vr",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "rec_rent",
      workspaceId,
      kind: "expense",
      frequency: "monthly",
      interval: 1,
      startDate: format(setDate(monthStart, 5), "yyyy-MM-dd"),
      description: "Aluguel",
      amount: 750,
      centerId: centerIds.shared,
      categoryId: getCategory("aluguel"),
      paymentMethod: "pix",
      installments: 1,
      createdAt: now,
      updatedAt: now,
    },
  ];

  const vehicle: Vehicle = {
    id: "vehicle_cg160",
    workspaceId,
    centerId: centerIds.moto,
    brand: "Honda",
    model: "CG 160",
    year: 2021,
    nickname: "CG 160 2021",
    fuelType: "Gasolina",
    currentOdometerKm: 28740,
    createdAt: now,
    updatedAt: now,
  };

  const fuelLogs: FuelLog[] = [
    {
      id: "fuel_1",
      workspaceId,
      centerId: centerIds.moto,
      vehicleId: vehicle.id,
      date: subDays(new Date(), 1).toISOString().slice(0, 10),
      odometerKm: 28740,
      totalCost: 78,
      pricePerLiter: 6.49,
      liters: round(78 / 6.49),
      station: "Shell Jardim Primavera",
      notes: "Abastecimento para a semana",
      paymentMethod: "debit",
      transactionId: "tx_fuel_1",
      createdAt: now,
      updatedAt: now,
    },
  ];

  const maintenanceLogs: MaintenanceLog[] = [
    {
      id: "maint_1",
      workspaceId,
      centerId: centerIds.moto,
      vehicleId: vehicle.id,
      date: subDays(new Date(), 10).toISOString().slice(0, 10),
      odometerKm: 28610,
      type: "Troca preventiva",
      category: "troca-de-oleo",
      description: "Troca de óleo + filtro",
      totalCost: 120,
      shop: "Oficina da esquina",
      notes: "Moto ficou mais silenciosa",
      recurringMonths: 4,
      recurringKm: 2000,
      transactionId: "tx_maint_1",
      createdAt: now,
      updatedAt: now,
    },
  ];

  const operationalSettings: OperationalSettings = {
    energyRatePerKwh: 1.15,
    printerPowerWatts: 80,
    extraFixedCostPerProduction: 2,
    manualLaborRatePerHour: 12,
  };

  const filamentSpools: FilamentSpool[] = [
    {
      id: "spool_white",
      workspaceId,
      centerId: centerIds.store,
      name: "PLA Branco",
      material: "PLA",
      color: "Branco",
      brand: "Voolt3D",
      nominalWeightGrams: 1000,
      remainingWeightGrams: 885,
      purchaseCost: 50,
      costPerGram: 0.05,
      purchaseDate: subDays(new Date(), 14).toISOString().slice(0, 10),
      supplier: "Mercado Livre",
      lot: "A1-BR-01",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "spool_blue",
      workspaceId,
      centerId: centerIds.store,
      name: "PLA Azul",
      material: "PLA",
      color: "Azul",
      brand: "Voolt3D",
      nominalWeightGrams: 1000,
      remainingWeightGrams: 955,
      purchaseCost: 50,
      costPerGram: 0.05,
      purchaseDate: subDays(new Date(), 14).toISOString().slice(0, 10),
      supplier: "Mercado Livre",
      lot: "A1-AZ-01",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "spool_black",
      workspaceId,
      centerId: centerIds.store,
      name: "PLA Preto",
      material: "PLA",
      color: "Preto",
      brand: "Voolt3D",
      nominalWeightGrams: 1000,
      remainingWeightGrams: 1000,
      purchaseCost: 50,
      costPerGram: 0.05,
      purchaseDate: subDays(new Date(), 14).toISOString().slice(0, 10),
      supplier: "Mercado Livre",
      lot: "A1-PT-01",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "spool_green",
      workspaceId,
      centerId: centerIds.store,
      name: "PLA Verde",
      material: "PLA",
      color: "Verde",
      brand: "Voolt3D",
      nominalWeightGrams: 1000,
      remainingWeightGrams: 1000,
      purchaseCost: 50,
      costPerGram: 0.05,
      purchaseDate: subDays(new Date(), 14).toISOString().slice(0, 10),
      supplier: "Mercado Livre",
      lot: "A1-VD-01",
      createdAt: now,
      updatedAt: now,
    },
  ];

  const supplyItems: SupplyItem[] = [
    {
      id: "supply_primer",
      workspaceId,
      centerId: centerIds.store,
      name: "Primer branco",
      category: "Primer branco",
      unit: "ml",
      totalQuantity: 900,
      remainingQuantity: 780,
      totalCost: 28,
      unitCost: round(28 / 900),
      purchaseDate: subDays(new Date(), 12).toISOString().slice(0, 10),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "supply_verniz",
      workspaceId,
      centerId: centerIds.store,
      name: "Verniz fosco",
      category: "Verniz",
      unit: "ml",
      totalQuantity: 500,
      remainingQuantity: 460,
      totalCost: 18,
      unitCost: round(18 / 500),
      purchaseDate: subDays(new Date(), 12).toISOString().slice(0, 10),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "supply_package",
      workspaceId,
      centerId: centerIds.store,
      name: "Saquinhos zip",
      category: "Embalagem",
      unit: "unit",
      totalQuantity: 50,
      remainingQuantity: 42,
      totalCost: 20,
      unitCost: round(20 / 50),
      purchaseDate: subDays(new Date(), 12).toISOString().slice(0, 10),
      createdAt: now,
      updatedAt: now,
    },
  ];

  const materialCost = round(100 * 0.05 + 40 * 0.05);
  const wasteCost = round(15 * 0.05 + 5 * 0.05);
  const energyCost = round((operationalSettings.printerPowerWatts / 1000) * 6.5 * operationalSettings.energyRatePerKwh);
  const primerCost = round(120 * (28 / 900));
  const vernizCost = round(40 * (18 / 500));
  const packagingCost = round(8 * (20 / 50));
  const supplyCost = round(primerCost + vernizCost);
  const finishingCost = round(1.5 * operationalSettings.manualLaborRatePerHour);
  const totalCost = round(
    materialCost +
      wasteCost +
      energyCost +
      supplyCost +
      packagingCost +
      finishingCost +
      operationalSettings.extraFixedCostPerProduction +
      5,
  );
  const unitCost = round(totalCost / 10);
  const recognizedCost = round(unitCost * 8);
  const saleTotal = 144;
  const grossProfit = round(saleTotal - recognizedCost);
  const marginPercent = round((grossProfit / saleTotal) * 100);

  const productionJobs: ProductionJob[] = [
    {
      id: "production_1",
      workspaceId,
      centerId: centerIds.store,
      name: "Topo Stitch",
      client: "Ana Paula",
      date: subDays(new Date(), 3).toISOString().slice(0, 10),
      quantityProduced: 10,
      quantitySold: 8,
      status: "delivered",
      printHours: 6.5,
      finishingHours: 1.5,
      additionalManualCost: 5,
      packagingCost,
      salePriceUnit: 18,
      salePriceTotal: saleTotal,
      notes: "Pintura leve e acabamento manual",
      energyCost,
      materialCost,
      wasteCost,
      supplyCost,
      finishingCost,
      totalCost,
      unitCost,
      grossProfit,
      marginPercent,
      createdAt: now,
      updatedAt: now,
    },
  ];

  const productionMaterialUsages: ProductionMaterialUsage[] = [
    {
      id: "usage_white",
      workspaceId,
      productionJobId: "production_1",
      itemKind: "filament",
      itemId: "spool_white",
      itemName: "PLA Branco",
      quantity: 100,
      wasteQuantity: 15,
      unitCost: 0.05,
      totalCost: round((100 + 15) * 0.05),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "usage_blue",
      workspaceId,
      productionJobId: "production_1",
      itemKind: "filament",
      itemId: "spool_blue",
      itemName: "PLA Azul",
      quantity: 40,
      wasteQuantity: 5,
      unitCost: 0.05,
      totalCost: round((40 + 5) * 0.05),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "usage_primer",
      workspaceId,
      productionJobId: "production_1",
      itemKind: "supply",
      itemId: "supply_primer",
      itemName: "Primer branco",
      quantity: 120,
      wasteQuantity: 0,
      unitCost: round(28 / 900),
      totalCost: primerCost,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "usage_verniz",
      workspaceId,
      productionJobId: "production_1",
      itemKind: "supply",
      itemId: "supply_verniz",
      itemName: "Verniz fosco",
      quantity: 40,
      wasteQuantity: 0,
      unitCost: round(18 / 500),
      totalCost: vernizCost,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "usage_package",
      workspaceId,
      productionJobId: "production_1",
      itemKind: "supply",
      itemId: "supply_package",
      itemName: "Saquinhos zip",
      quantity: 8,
      wasteQuantity: 0,
      unitCost: round(20 / 50),
      totalCost: packagingCost,
      createdAt: now,
      updatedAt: now,
    },
  ];

  const stockMovements: StockMovement[] = [
    ...filamentSpools.map((spool) => ({
      id: `move_purchase_${spool.id}`,
      workspaceId,
      centerId: centerIds.store,
      itemKind: "filament" as const,
      itemId: spool.id,
      movementKind: "purchase" as const,
      quantity: spool.nominalWeightGrams,
      unitCost: spool.costPerGram,
      totalCost: spool.purchaseCost,
      occurredAt: spool.purchaseDate,
      createdAt: now,
      updatedAt: now,
    })),
    {
      id: "move_consume_spool_white",
      workspaceId,
      centerId: centerIds.store,
      itemKind: "filament",
      itemId: "spool_white",
      movementKind: "consume",
      quantity: 100,
      unitCost: 0.05,
      totalCost: 5,
      occurredAt: subDays(new Date(), 3).toISOString().slice(0, 10),
      relatedProductionJobId: "production_1",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "move_waste_spool_white",
      workspaceId,
      centerId: centerIds.store,
      itemKind: "filament",
      itemId: "spool_white",
      movementKind: "waste",
      quantity: 15,
      unitCost: 0.05,
      totalCost: 0.75,
      occurredAt: subDays(new Date(), 3).toISOString().slice(0, 10),
      relatedProductionJobId: "production_1",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "move_consume_spool_blue",
      workspaceId,
      centerId: centerIds.store,
      itemKind: "filament",
      itemId: "spool_blue",
      movementKind: "consume",
      quantity: 40,
      unitCost: 0.05,
      totalCost: 2,
      occurredAt: subDays(new Date(), 3).toISOString().slice(0, 10),
      relatedProductionJobId: "production_1",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "move_waste_spool_blue",
      workspaceId,
      centerId: centerIds.store,
      itemKind: "filament",
      itemId: "spool_blue",
      movementKind: "waste",
      quantity: 5,
      unitCost: 0.05,
      totalCost: 0.25,
      occurredAt: subDays(new Date(), 3).toISOString().slice(0, 10),
      relatedProductionJobId: "production_1",
      createdAt: now,
      updatedAt: now,
    },
    ...supplyItems.map((item) => ({
      id: `move_purchase_${item.id}`,
      workspaceId,
      centerId: centerIds.store,
      itemKind: "supply" as const,
      itemId: item.id,
      movementKind: "purchase" as const,
      quantity: item.totalQuantity,
      unitCost: item.unitCost,
      totalCost: item.totalCost,
      occurredAt: item.purchaseDate,
      createdAt: now,
      updatedAt: now,
    })),
    {
      id: "move_consume_primer",
      workspaceId,
      centerId: centerIds.store,
      itemKind: "supply",
      itemId: "supply_primer",
      movementKind: "consume",
      quantity: 120,
      unitCost: round(28 / 900),
      totalCost: primerCost,
      occurredAt: subDays(new Date(), 3).toISOString().slice(0, 10),
      relatedProductionJobId: "production_1",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "move_consume_verniz",
      workspaceId,
      centerId: centerIds.store,
      itemKind: "supply",
      itemId: "supply_verniz",
      movementKind: "consume",
      quantity: 40,
      unitCost: round(18 / 500),
      totalCost: vernizCost,
      occurredAt: subDays(new Date(), 3).toISOString().slice(0, 10),
      relatedProductionJobId: "production_1",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "move_consume_package",
      workspaceId,
      centerId: centerIds.store,
      itemKind: "supply",
      itemId: "supply_package",
      movementKind: "consume",
      quantity: 8,
      unitCost: round(20 / 50),
      totalCost: packagingCost,
      occurredAt: subDays(new Date(), 3).toISOString().slice(0, 10),
      relatedProductionJobId: "production_1",
      createdAt: now,
      updatedAt: now,
    },
  ];

  const storeOrders: StoreOrder[] = [
    {
      id: "order_1",
      workspaceId,
      centerId: centerIds.store,
      client: "Ana Paula",
      productName: "Topo Stitch",
      quantity: 8,
      date: subDays(new Date(), 2).toISOString().slice(0, 10),
      status: "delivered",
      unitPrice: 18,
      totalPrice: saleTotal,
      totalCostSnapshot: recognizedCost,
      grossProfit,
      linkedProductionJobId: "production_1",
      incomeId: "income_store_order_1",
      notes: "Pedido entregue via retirada local",
      createdAt: now,
      updatedAt: now,
    },
  ];

  const settings: AppSettings = {
    currency: "BRL",
    locale: "pt-BR",
    theme: "dark",
    salaryMonthly: 2000,
    vrMonthly: 800,
    salaryDay: 5,
    vrDay: 3,
    activeCenterIds: costCenters.map((center) => center.id),
    storageMode,
  };

  return {
    version: 1,
    user: {
      id: userId,
      username,
      displayName,
      email,
      avatarUrl: null,
      role: "owner",
      createdAt: now,
      updatedAt: now,
    },
    workspace: {
      id: workspaceId,
      name: workspaceName,
      slug: slugify(workspaceName),
      currency: "BRL",
      timezone: "America/Sao_Paulo",
      ownerUserId: userId,
      isPersonal: true,
      branding: {
        appName: workspaceName,
        accent: "#10b981",
        logoMode: "glyph",
      },
      createdAt: now,
      updatedAt: now,
    },
    costCenters,
    categories,
    cards,
    transactions,
    installments,
    incomes,
    budgets,
    recurrences,
    vehicles: [vehicle],
    fuelLogs,
    maintenanceLogs,
    operationalSettings,
    filamentSpools,
    supplyItems,
    stockMovements,
    productionJobs,
    productionMaterialUsages,
    storeOrders,
    settings,
    meta: {
      schemaVersion,
      seededAt: now,
      updatedAt: now,
      importedFromLocalAt: null,
      lastMergedAt: null,
      lastMergedHash: null,
      migrationOrigin: null,
      dirty: false,
      source: "seed",
      storageMode,
      appVersion,
    },
  };
}
